### ISSUE TITLE
Rear facing camera doesn't work in iOS 11 Safari 11

### ISSUE THREAD

**Issue by bthornic** [JodusNodus/react-qr-reader#39] opened 2017-10-14 22:10 UTC
Hi,

It seems to be front facing only. I've tried using facingMode="environment" and facingMode="rear". Seems to only work in Android. Any ideas?

**Comment by JodusNodus** [comment] 2017-10-15 14:30
Duplicate of #37

**Closed by JodusNodus** 2017-10-15 14:30 UTC
