### ISSUE TITLE
OverconstrainedError

### ISSUE THREAD

**Issue by gdromero** [JodusNodus/react-qr-reader#3] opened 2016-06-29 15:19 UTC
When I use the library in firefox this error is displayed in console:

OverconstrainedError

but not in chrome. 

Any idea?

**Comment by JodusNodus** [comment] 2016-06-29 15:30
I was not able to reproduce the error. Can you give more information about your environment (firefox version, os, react-qr-reader version).

**Comment by gdromero** [comment] 2016-06-29 15:40
firefox: 47.0
os: linux
react-qr-reader: 0.2.5

**Comment by gdromero** [comment] 2016-06-29 15:43
When I open the example (https://jodusnodus.github.io/react-qr-reader/) works fine

**Comment by JodusNodus** [comment] 2016-06-29 15:48
Normally this error is fired by the getUserMedia api when the webcam is not compatible. [link](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)
I'm going to test it on my desktop running Arch Linux.

**Comment by JodusNodus** [comment] 2016-06-29 15:53
I was not able to reproduce the error on my machine. Have you tried cloning the repository and `npm i && npm run storybook`?

**Comment by gdromero** [comment] 2016-06-29 17:37
result of `npm i && npm run storybook` after clone repository

ERROR in multi preview
Module not found: Error: Cannot resolve module 'webpack-hot-middleware/client' in /home/gdromero/Downloads/react-qr-reader-master
 @ multi preview

ERROR in multi preview
Module not found: Error: Cannot resolve module 'babel' in /home/gdromero/Downloads/react-qr-reader-master
 @ multi preview

**Comment by JodusNodus** [comment] 2016-06-29 18:37
I have just tested this on a clean ubuntu install, you should be able install the dependencies and then run the test with `npm run storybook`.

**Comment by gdromero** [comment] 2016-06-30 17:40
![screenshot](https://cloud.githubusercontent.com/assets/4448617/16498076/67a38500-3ed0-11e6-88bb-3979f7435809.png)

this is that I saw when run the example

**Comment by JodusNodus** [comment] 2016-06-30 17:43
What webcam are you using and does the demo work in chrome?

**Comment by gdromero** [comment] 2016-06-30 18:59
I tested your demo on a clean ubuntu install in other machine with firefox 47 and produce the same result: OverconstrainedError

**Comment by JodusNodus** [comment] 2016-06-30 21:49
What is the resolution of the webcam?

**Comment by JodusNodus** [comment] 2016-06-30 22:22
I was able to reproduce the error. The problem was that i set the minimum resolution at 720p. I lowered the minimum resolution to 360p. i published it as version 0.2.6. If it works than we can close the issue.
👍

**Comment by gdromero** [comment] 2016-07-01 11:13
great! When you upload the new version I test it. Thanks

**Comment by JodusNodus** [comment] 2016-07-01 11:16
It is already published to npm as version 0.2.6

**Comment by gdromero** [comment] 2016-07-01 11:25
Its works! Very good job. Thanks

**Closed** 2016-07-01 11:27 UTC

**Comment by joaodgv** [comment] 2020-10-31 20:23
Hi! I'm trying to use your code with react and it's giving me this error. The demo works for me so it should be something on my code. Anyway to know what could be causing this problem?
