### ISSUE TITLE
Babel Presets Error during installation

### ISSUE THREAD

**Issue by MarcCloud** [JodusNodus/react-qr-reader#22] opened 2017-03-31 18:42 UTC
Hi, I tried installing the library but I get the following error when running it using webpack dev server:

Error in ./~/react-qr-reader/lib/index.js
Module build failed: Error: Couldn't find preset "stage-0" relative to directory "/node_modules/react-qr-reader"
    at Array.map (native)
 @ ./app/approvals/code-scanner.js 27:21-47
 @ ./app/approvals/approvals.js
 @ ./app/approvals/index.js
 @ ./app/App.js
 @ ./app/index.js
 @ multi ./config/polyfills.js ./app/index.js

I shouldn't need to install those deps.

**Comment by JodusNodus** [comment] 2017-04-01 13:36
No indeed shouldn’t have to i will try to reproduce your error.

**Comment by JodusNodus** [comment] 2017-04-08 10:51
I am not able to reproduce your error. There is no requirement for the `babel-preset-stage-0` package. It is only used for building the lib files. It seems like you are using polyfills  (`@ multi ./config/polyfills.js ./app/index.js`) your problem is probably there. Let me know how it works out.

**Comment by JodusNodus** [comment] 2017-04-18 16:02
I am closing this because you seem to be the only one having this problem and it is probably not caused by react-qr-reader. If it is, please reopen it.

**Closed by JodusNodus** 2017-04-18 16:02 UTC
